# Generated by Django 2.2.24 on 2023-02-10 13:57

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def fill_new_building_in_flats(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    flat = apps.get_model('property', 'Flat')
    new_building_flats = flat.objects.filter(construction_year__gte=2015)
    old_building_flats = flat.objects.filter(construction_year__lte=2014)
    if new_building_flats.exists():
        new_building_flats.update(new_building=True)
    if old_building_flats.exists():
        old_building_flats.update(new_building=False)


def move_backward(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    flat = apps.get_model('property', 'Flat')
    flats = flat.objects.all()
    if flats.exists():
        flats.update(new_building=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_in_flats, move_backward),
    ]
