# Generated by Django 2.2.24 on 2023-02-10 13:57

from django.db import migrations


def fill_new_building_in_flats(apps, schema_editor):
    flat = apps.get_model('property', 'Flat')
    for flat in flat.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building = True
            flat.save()


def move_backward(apps, schema_editor):
    flat = apps.get_model('property', 'Flat')
    for flat in flat.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building = None
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_in_flats, move_backward),
    ]
