# Generated by Django 2.2.24 on 2023-02-10 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='like',
            field=models.ManyToManyField(
                related_name='flat_likes',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Кто лайкнул'
            ),
        ),
    ]
