# Generated by Django 2.2.24 on 2023-02-10 15:43

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from phonenumber_field.phonenumber import PhoneNumber


def fill_owner_pure_phone_in_flats(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    flat = apps.get_model('property', 'Flat')
    for flat in flat.objects.all():
        number_phone = PhoneNumber.from_string(
            flat.owners_phonenumber,
            region='RU'
        )
        if number_phone.is_valid():
            flat.owner_pure_phone = number_phone
            flat.save()
        else:
            print(f"\nНомер {flat.owners_phonenumber} не валидный для владельца с ID={flat.pk}")


def move_backward(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    flat = apps.get_model('property', 'Flat')
    for flat in flat.objects.all():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone_in_flats, move_backward),
    ]
