# Generated by Django 2.2.24 on 2023-02-10 15:43

from django.db import migrations
from phonenumber_field.phonenumber import PhoneNumber

def fill_owner_pure_phone_in_flats(apps, schema_editor):
    flat = apps.get_model('property', 'Flat')
    for flat in flat.objects.all():
        flat.owner_pure_phone = PhoneNumber.from_string(
            flat.owners_phonenumber,
            region='RU'
        )
        flat.save()


def move_backward(apps, schema_editor):
    flat = apps.get_model('property', 'Flat')
    for flat in flat.objects.all():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone_in_flats, move_backward),
    ]
