# Generated by Django 2.2.24 on 2023-02-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230213_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='like',
            new_name='likes',
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
    ]
