# Generated by Django 2.2.24 on 2023-02-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20230213_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='formatted_phone',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phone',
        ),
    ]
