# Generated by Django 2.2.24 on 2023-02-13 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20230213_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_flat',
        ),
        migrations.AddField(
            model_name='complaint',
            name='flat',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='complaints',
                to='property.Flat',
                verbose_name='Квартира, на которую жаловались'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='complaining_users',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Кто жаловался'
            ),
        ),
    ]
