# Generated by Django 2.2.24 on 2023-02-14 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20230213_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='complaints',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Кто жаловался'
            ),
        ),
    ]
